version: 2.1
jobs:

  build:
    docker:
      - image: circleci/node:13.0.1
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2.1
  build:
    jobs:
      - build